export const AuthTypes = {
  //Auth
  VERYFY_AUTHENTICATE: "VERYFY_AUTHENTICATE",
  POST_AUTHENTICATE: "POST_AUTHENTICATE",
  DATA_USER: "DATA_USER",
  UPDATE_MESSAGE: "UPDATE_MESSAGE",
  ERROR_AUTHENTICATE: "ERROR_AUTHENTICATE",

  SUCESS_MESSAGE: "SUCESS_MESSAGE",
  ERROR_MESSAGE: "ERROR_MESSAGE",
};
